### PR TITLE
Update FlightsMap.php

### PR DESCRIPTION
**Pull request by derrobin154**
If you set the page to public you get an error because $user does not exist, so you have to check if $user exists.

### CODE REVIEW

**Comment by FatihKoz** [comment]
I did not though using maps on a public page in the first place, even the user pireps map should be visible only to the user itself not others. Thus I never needed to check `$user`

Do you really want to use maps in public pages ?

**Comment by derrobin154** [comment]
In fact, this is intentional with us, for whatever reason (I'm just the dev) but a security check is always good.

**Comment by FatihKoz** [comment]
It is ok for me and thanks for pull request ... If you need/want to display user pirep's on a public page, then we need to change the core more 'cause it gets the user's pireps from Auth::user. And that will not work on a public page, visitor of that page will only see a blank map (or as far as I remember, the button will not show up at all).

Just for your info.

**Comment by derrobin154** [comment]
In fact, I just had to remove auth in the service provider and add this security check to get the page to show up for me.

**Comment by derrobin154** [comment]
(in the service provider for DisposableHubs)

**Comment by FatihKoz** [comment]
If you are happy with the result, it is ok :)

**Pull request merged**
